apiVersion: v1
kind: Service
metadata:
  name: rest-app-service
spec:
  selector:
    app: rest-app
  ports:
  - protocol: "TCP"
    port: 5004
    targetPort: 5004
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-app
spec:
  selector:
    matchLabels:
      app: rest-app
  replicas: 1
  template:
    metadata:
      labels:
        app: rest-app
    spec:
      containers:
      - name: rest-app
        image: localhost:5000/rest-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5004